# Importing Library

In [1]:
import numpy as np


# Array Attributes

In [2]:
a = np.array([1, 2, 3]) #1D array / Vector

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a.ndim

1

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b.ndim

2

In [12]:
c = np.array([[[1, 2, 3], [4, 5, 6]],
             
             [[1, 2, 3], [4, 5, 6]]])

In [21]:
a.size, b.size #determine how many elements are there in that array

(3, 9)

In [13]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
c.shape

(2, 2, 3)

In [18]:
a.dtype, b.dtype, c.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [23]:
a.nbytes, b.nbytes, c.nbytes

(12, 36, 48)

# Array Cration

In [25]:
array1 = np.array([1, 2, 3], dtype = 'float')

In [26]:
array1

array([1., 2., 3.])

In [27]:
zeros = np.zeros((4, 4), dtype = 'int')  # (shape, dtype)

In [28]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
ones = np.ones((3, 4), dtype = 'int')

In [31]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
full = np.full((5, 6), 18, dtype = 'int')

In [33]:
full

array([[18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18]])

In [34]:
identity = np.identity(4)

In [35]:
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
eye = np.eye(4)

In [37]:
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
eye1 = np.eye(4, 4, 1)

In [39]:
eye1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [40]:
eye2 = np.eye(4, 4, 2)

In [41]:
eye2

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
eye3 = np.eye(4, 4, -1)

In [43]:
eye3

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
arange = np.arange(1, 20)

In [45]:
arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [46]:
arange1 = np.arange(1, 20, 2)

In [47]:
arange1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
linspace = np.linspace(1, 100, 10)

In [49]:
linspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [52]:
linspace1 = np.linspace(1, 10, 20, dtype = 'int')

In [53]:
linspace1

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [54]:
linspace2 = np.linspace(1, 5, 15)

In [55]:
linspace2

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [57]:
empty = np.empty((1, 8))

In [58]:
empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 6.64024228e-321,
        6.23057348e-307, 1.42419530e-306]])

In [61]:
for i in range(8) :
    empty[:, i] = i


In [62]:
empty

array([[0., 1., 2., 3., 4., 5., 6., 7.]])

# Array indexing and slicing

In [64]:
arr1 = np.array([1, 2, 3, 4, 5])

In [65]:
print(arr1)

[1 2 3 4 5]


In [66]:
arr1[0]

1

In [68]:
arr1[3]

4

In [69]:
arr1[-1]

5

In [71]:
arr1[-5]

1

In [74]:
arr2 = np.random.randint(1, 20, size = (3, 4))

In [75]:
print(arr2)

[[ 9 15 14 18]
 [17  1  8  8]
 [ 3  7 18 17]]


In [76]:
arr2[1][2]

8

In [77]:
arr2[1, 2]

8

In [78]:
arr3 = np.random.randint(1, 50, size = (3, 4, 3))

In [79]:
arr3

array([[[27, 47, 14],
        [31, 49, 46],
        [38, 35, 39],
        [37, 38, 15]],

       [[ 5, 21, 21],
        [31,  9,  8],
        [37, 44, 42],
        [26, 39, 28]],

       [[39,  8, 44],
        [37,  3, 38],
        [32,  5, 43],
        [17, 28, 35]]])

In [80]:
arr3[0][1][1]

49

In [81]:
arr3[0, 1, 1]

49

In [82]:
print(arr1)

[1 2 3 4 5]


In [83]:
print(arr1[0 : 3])

[1 2 3]


In [84]:
arr1[2 : ]

array([3, 4, 5])

In [85]:
print(arr2)

[[ 9 15 14 18]
 [17  1  8  8]
 [ 3  7 18 17]]


In [87]:
print(arr2[0 : 2, 0 : 2]) # (row, clm)

[[ 9 15]
 [17  1]]


In [89]:
print(arr2[1 : 3, 2 : 4])

[[ 8  8]
 [18 17]]


## Array Shape 

In [90]:
ar = np.array([[1, 2, 3], [4, 5, 6]])

In [91]:
print(ar)

[[1 2 3]
 [4 5 6]]


In [92]:
ar.shape

(2, 3)

In [96]:
ar_reshape = np.reshape(ar, (3, 2))

In [97]:
print(ar_reshape)

[[1 2]
 [3 4]
 [5 6]]


In [99]:
ar_reshape.shape

(3, 2)

In [100]:
ar_reshape1 = np.reshape(ar, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [101]:
ar_resize = np.resize(ar, (3, 3))

In [102]:
print(ar_resize)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [103]:
ar_ravel = np.ravel(ar)   # convert n dimentional into 1 dimentional

In [105]:
print(ar_ravel)

[1 2 3 4 5 6]


In [106]:
ar_ravel.shape

(6,)

In [108]:
ar_flatten = ar.flatten() #return a copy of array, always allocates a new memory

In [109]:
print(ar_flatten)

[1 2 3 4 5 6]


In [110]:
ar_ravel[0] = 100

In [111]:
print(ar)

[[100   2   3]
 [  4   5   6]]


In [112]:
ar_flatten[0] = 0

In [113]:
print(ar)

[[100   2   3]
 [  4   5   6]]


In [114]:
print(ar_flatten)

[0 2 3 4 5 6]


### defining a array shape

In [115]:
ar.shape = (3, 2)

In [116]:
print(ar)

[[100   2]
 [  3   4]
 [  5   6]]


In [117]:
ar.shape = (2, 3)

In [118]:
print(ar)

[[100   2   3]
 [  4   5   6]]


In [119]:
aa = np.random.randint(1,100, size = (2, 3))

In [120]:
print(aa)

[[40 93 84]
 [ 9 58 68]]


In [121]:
bb = 2 * aa

In [122]:
print(bb)

[[ 80 186 168]
 [ 18 116 136]]


In [123]:
np.hstack((aa, bb))

array([[ 40,  93,  84,  80, 186, 168],
       [  9,  58,  68,  18, 116, 136]])

In [124]:
np.column_stack((aa, bb))

array([[ 40,  93,  84,  80, 186, 168],
       [  9,  58,  68,  18, 116, 136]])

In [125]:
np.concatenate((aa, bb), axis = 1)

array([[ 40,  93,  84,  80, 186, 168],
       [  9,  58,  68,  18, 116, 136]])

### Vertical stack

In [127]:
np.vstack((aa, bb))

array([[ 40,  93,  84],
       [  9,  58,  68],
       [ 80, 186, 168],
       [ 18, 116, 136]])

In [128]:
np.concatenate((aa, bb), axis = 0)

array([[ 40,  93,  84],
       [  9,  58,  68],
       [ 80, 186, 168],
       [ 18, 116, 136]])

In [129]:
np.row_stack((aa, bb))

array([[ 40,  93,  84],
       [  9,  58,  68],
       [ 80, 186, 168],
       [ 18, 116, 136]])

### Depth Stack

In [130]:
np.dstack((aa, bb))

array([[[ 40,  80],
        [ 93, 186],
        [ 84, 168]],

       [[  9,  18],
        [ 58, 116],
        [ 68, 136]]])